"""Offline helper defaults. No implicit paid API enablement or invented prices."""
DOCUMENTARY_VIDEO_WIDTH = 1920
DOCUMENTARY_VIDEO_HEIGHT = 1080
DOCUMENTARY_COST_TRACKING_ENABLED = False
DOCUMENTARY_COST_TEXT_INPUT_PER_1M_TOKENS = None
DOCUMENTARY_COST_TEXT_OUTPUT_PER_1M_TOKENS = None
DOCUMENTARY_COST_TTS_PER_1K_CHARS = None
DOCUMENTARY_COST_IMAGE_PER_IMAGE = None
DOCUMENTARY_COST_VEO_PER_SECOND = None
